import {MigrationInterface, QueryRunner} from "typeorm";

export class patientsPopulate1621955915349 implements MigrationInterface {

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`INSERT INTO patients (id, name, document, email, plan_number) VALUES (uuid_generate_v4(), 'Luiza Correia Rodrigues', '91633041042', 'luizacorreiarodrigues@gmail.com', '1')`);
        await queryRunner.query(`INSERT INTO patients (id, name, document, email, plan_number) VALUES (uuid_generate_v4(), 'Alice Oliveira Cunha', '92687147010', 'aliceoliveiracunha@gmail.com', '2')`);
        await queryRunner.query(`INSERT INTO patients (id, name, document, email, plan_number) VALUES (uuid_generate_v4(), 'Vinicius Ribeiro Almeida', '27809858017', 'viniciusribeiroalmeida@gmail.com', '3')`);
        await queryRunner.query(`INSERT INTO patients (id, name, document, email, plan_number) VALUES (uuid_generate_v4(), 'Otávio Correia Silva', '09537231003', 'otaviocorreiasilva@gmail.com', '4')`);
        await queryRunner.query(`INSERT INTO patients (id, name, document, email, plan_number) VALUES (uuid_generate_v4(), 'Kauan Pinto Correia', '27439897005', 'kauanpintocorreia@gmail.com', '5')`);
        await queryRunner.query(`INSERT INTO patients (id, name, document, email, plan_number) VALUES (uuid_generate_v4(), 'Letícia Pinto Goncalves', '45051781020', 'leticiapintogoncalves@gmail.com', '6')`);
        await queryRunner.query(`INSERT INTO patients (id, name, document, email, plan_number) VALUES (uuid_generate_v4(), 'Alex Almeida Sousa', '45569194010', 'alexalmeidasousa@gmail.com', '7')`);
        await queryRunner.query(`INSERT INTO patients (id, name, document, email, plan_number) VALUES (uuid_generate_v4(), 'Aline Sousa Ferreira', '20457567007', 'alinesousaferreira@gmail.com', '8')`);
        await queryRunner.query(`INSERT INTO patients (id, name, document, email, plan_number) VALUES (uuid_generate_v4(), 'Emilly Azevedo Ferreira', '26178101007', 'emilyazevedoferreira@gmail.com', '9')`);
        await queryRunner.query(`INSERT INTO patients (id, name, document, email, plan_number) VALUES (uuid_generate_v4(), 'Antônio Gomes Cunha', '44576594010', 'antoniogomescunha@gmail.com', '10')`);
        await queryRunner.query(`INSERT INTO patients (id, name, document, email, plan_number) VALUES (uuid_generate_v4(), 'Isabela Goncalves Pinto', '38712454028', 'isabelagoncalvespinto@gmail.com', '11')`);
        await queryRunner.query(`INSERT INTO patients (id, name, document, email, plan_number) VALUES (uuid_generate_v4(), 'Júlia Ribeiro Alves', '97937215020', 'juliaribeiroalves@gmail.com', '12')`);
        await queryRunner.query(`INSERT INTO patients (id, name, document, email, plan_number) VALUES (uuid_generate_v4(), 'Vitória Souza Sousa', '65730970099', 'vitoriasouzasousa@gmail.com', '13')`);
        await queryRunner.query(`INSERT INTO patients (id, name, document, email, plan_number) VALUES (uuid_generate_v4(), 'Evelyn Goncalves Melo', '94777585077', 'evelyngoncalvesmelo@gmail.com', '14')`);
        await queryRunner.query(`INSERT INTO patients (id, name, document, email, plan_number) VALUES (uuid_generate_v4(), 'Sarah Lima Correia', '96724506050', 'sarahlimacorreia@gmail.com', '15')`);
        await queryRunner.query(`INSERT INTO patients (id, name, document, email, plan_number) VALUES (uuid_generate_v4(), 'Sofia Lima Pinto', '73972752067', 'sofialimapinto@gmail.com', '16')`);
        await queryRunner.query(`INSERT INTO patients (id, name, document, email, plan_number) VALUES (uuid_generate_v4(), 'Murilo Barbosa Cunha', '63476623025', 'murilobarbosacunha@gmail.com', '17')`);
        await queryRunner.query(`INSERT INTO patients (id, name, document, email, plan_number) VALUES (uuid_generate_v4(), 'Maria Souza Cardoso', '52588095011', 'mariasouzacardoso@gmail.com', '18')`);
        await queryRunner.query(`INSERT INTO patients (id, name, document, email, plan_number) VALUES (uuid_generate_v4(), 'Ágatha Almeida Barbosa', '46752565031', 'agathaalmeidabarbosa@gmail.com', '19')`);
        await queryRunner.query(`INSERT INTO patients (id, name, document, email, plan_number) VALUES (uuid_generate_v4(), 'Martim Ribeiro Cavalcanti', '34205151039', 'martinribeirocavalcanti@gmail.com', '20')`);
        await queryRunner.query(`INSERT INTO patients (id, name, document, email, plan_number) VALUES (uuid_generate_v4(), 'Vitór Sousa Costa', '09653798090', 'vitorsousacosta@gmail.com', '21')`);
        await queryRunner.query(`INSERT INTO patients (id, name, document, email, plan_number) VALUES (uuid_generate_v4(), 'Ana Sousa Costa', '51771681071', 'anasousacosta@gmail.com', '22')`);
        await queryRunner.query(`INSERT INTO patients (id, name, document, email, plan_number) VALUES (uuid_generate_v4(), 'Beatriz Ribeiro Castro', '40819635090', 'beatrizribeirocastro@gmail.com', '23')`);
        await queryRunner.query(`INSERT INTO patients (id, name, document, email, plan_number) VALUES (uuid_generate_v4(), 'Carla Carvalho Melo', '74719358047', 'carlacarvalhomelo@gmail.com', '24')`);
        await queryRunner.query(`INSERT INTO patients (id, name, document, email, plan_number) VALUES (uuid_generate_v4(), 'Julia Rocha Goncalves', '77503574089', 'juliarochagoncalves@gmail.com', '25')`);
        await queryRunner.query(`INSERT INTO patients (id, name, document, email, plan_number) VALUES (uuid_generate_v4(), 'Leila Costa Almeida', '65350156020', 'leilacostaalmeida@gmail.com', '26')`);
        await queryRunner.query(`INSERT INTO patients (id, name, document, email, plan_number) VALUES (uuid_generate_v4(), 'Luis Araujo Barros', '48591463013', 'luisaraujobarros@gmail.com', '27')`);
        await queryRunner.query(`INSERT INTO patients (id, name, document, email, plan_number) VALUES (uuid_generate_v4(), 'Larissa Costa Goncalves', '73685141090', 'larissacostagoncalves@gmail.com', '28')`);
        await queryRunner.query(`INSERT INTO patients (id, name, document, email, plan_number) VALUES (uuid_generate_v4(), 'Antônio Martins Cardoso', '98977222036', 'antoniomartinscardoso@gmail.com', '29')`);
        await queryRunner.query(`INSERT INTO patients (id, name, document, email, plan_number) VALUES (uuid_generate_v4(), 'Melissa Alves Azevedo', '94987800055', 'melissaalvesazevedo@gmail.com', '30')`);
        await queryRunner.query(`INSERT INTO patients (id, name, document, email, plan_number) VALUES (uuid_generate_v4(), 'Aline Rocha Pereira', '31009469010', 'alinerochapereira@gmail.com', '31')`);
        await queryRunner.query(`INSERT INTO patients (id, name, document, email, plan_number) VALUES (uuid_generate_v4(), 'Marina Carvalho Sousa', '39071666042', 'marinacarvalhosousa@gmail.com', '32')`);
        await queryRunner.query(`INSERT INTO patients (id, name, document, email, plan_number) VALUES (uuid_generate_v4(), 'Gabriela Costa Cavalcanti', '58331246039', 'gabrielacostacavalcanti@gmail.com', '33')`);
        await queryRunner.query(`INSERT INTO patients (id, name, document, email, plan_number) VALUES (uuid_generate_v4(), 'Antônio Carvalho Melo', '32976847045', 'antoniocarvalhomelo@gmail.com', '34')`);
        await queryRunner.query(`INSERT INTO patients (id, name, document, email, plan_number) VALUES (uuid_generate_v4(), 'Alice Cunha Souza', '57500481012', 'alicecunhasouza@gmail.com', '35')`);
        await queryRunner.query(`INSERT INTO patients (id, name, document, email, plan_number) VALUES (uuid_generate_v4(), 'Kauê Azevedo Goncalves', '65154888073', 'kaueazevedogoncalves@gmail.com', '36')`);
        await queryRunner.query(`INSERT INTO patients (id, name, document, email, plan_number) VALUES (uuid_generate_v4(), 'Mateus Castro Goncalves', '45991659052', 'mateuscastrogoncalves@gmail.com', '37')`);
        await queryRunner.query(`INSERT INTO patients (id, name, document, email, plan_number) VALUES (uuid_generate_v4(), 'Felipe Cardoso Araujo', '67327261028', 'felipecardosoaraujo@gmail.com', '38')`);
        await queryRunner.query(`INSERT INTO patients (id, name, document, email, plan_number) VALUES (uuid_generate_v4(), 'Manuela Silva Cunha', '26727588082', 'manuelasilvacunha@gmail.com', '39')`);
        await queryRunner.query(`INSERT INTO patients (id, name, document, email, plan_number) VALUES (uuid_generate_v4(), 'Kauan Araujo Rodrigues', '20063789027', 'kauanaraujorodrigues@gmail.com', '40')`);
        await queryRunner.query(`INSERT INTO patients (id, name, document, email, plan_number) VALUES (uuid_generate_v4(), 'Luís Cavalcanti Lima', '31498629067', 'luiscavalcantilima@gmail.com', '41')`);
        await queryRunner.query(`INSERT INTO patients (id, name, document, email, plan_number) VALUES (uuid_generate_v4(), 'Eduardo Alves Ribeiro', '71623542030', 'eduardoalvesribeiro@gmail.com', '42')`);
        await queryRunner.query(`INSERT INTO patients (id, name, document, email, plan_number) VALUES (uuid_generate_v4(), 'Nicolas Ferreira Pinto', '85450610050', 'nicolasferreirapinto@gmail.com', '43')`);
        await queryRunner.query(`INSERT INTO patients (id, name, document, email, plan_number) VALUES (uuid_generate_v4(), 'João Dias Silva', '91819689069', 'joaodiassilva@gmail.com', '44')`);
        await queryRunner.query(`INSERT INTO patients (id, name, document, email, plan_number) VALUES (uuid_generate_v4(), 'Nicolas Almeida Cunha', '91334263094', 'nicolasalmeidacunha@gmail.com', '45')`);
        await queryRunner.query(`INSERT INTO patients (id, name, document, email, plan_number) VALUES (uuid_generate_v4(), 'Eduarda Melo Barros', '20699254043', 'eduardamelobarros@gmail.com', '46')`);
        await queryRunner.query(`INSERT INTO patients (id, name, document, email, plan_number) VALUES (uuid_generate_v4(), 'Lara Carvalho Ribeiro', '58034763071', 'laracarvalhoribeiro@gmail.com', '47')`);
        await queryRunner.query(`INSERT INTO patients (id, name, document, email, plan_number) VALUES (uuid_generate_v4(), 'Gabriel Cunha Azevedo', '26339218091', 'gabrielcunhaazevedo@gmail.com', '48')`);
        await queryRunner.query(`INSERT INTO patients (id, name, document, email, plan_number) VALUES (uuid_generate_v4(), 'Luiz Martins Barbosa', '36495407033', 'luizmartinsbarbosa@gmail.com', '49')`);
        await queryRunner.query(`INSERT INTO patients (id, name, document, email, plan_number) VALUES (uuid_generate_v4(), 'Lara Silva Pinto', '36330008019', 'larasilvapinto@gmail.com', '50')`);
        await queryRunner.query(`INSERT INTO patients (id, name, document, email, plan_number) VALUES (uuid_generate_v4(), 'Rafael Rodrigues Goncalves', '17426553000', 'rafaelrodriguesgoncalves@gmail.com', '51')`);
        await queryRunner.query(`INSERT INTO patients (id, name, document, email, plan_number) VALUES (uuid_generate_v4(), 'Gabriela Silva Barbosa', '49701948076', 'gabrielasilvabarbosa@gmail.com', '52')`);
        await queryRunner.query(`INSERT INTO patients (id, name, document, email, plan_number) VALUES (uuid_generate_v4(), 'Luan Rodrigues Lima', '05800586039', 'luanrodrigueslima@gmail.com', '53')`);
        await queryRunner.query(`INSERT INTO patients (id, name, document, email, plan_number) VALUES (uuid_generate_v4(), 'Maria Silva Almeida', '37411421073', 'mariasilvaalmeida@gmail.com', '54')`);
        await queryRunner.query(`INSERT INTO patients (id, name, document, email, plan_number) VALUES (uuid_generate_v4(), 'Manuela Sousa Santos', '35553972060', 'manuelasousasantos@gmail.com', '55')`);
        await queryRunner.query(`INSERT INTO patients (id, name, document, email, plan_number) VALUES (uuid_generate_v4(), 'Kauã Barbosa Correia', '99029919043', 'kauabarbosacorreia@gmail.com', '56')`);
        await queryRunner.query(`INSERT INTO patients (id, name, document, email, plan_number) VALUES (uuid_generate_v4(), 'Luís Fernandes Alves', '02860631070', 'luisfernandesalves@gmail.com', '57')`);
        await queryRunner.query(`INSERT INTO patients (id, name, document, email, plan_number) VALUES (uuid_generate_v4(), 'Fernanda Goncalves Araujo', '01760873039', 'fernandagoncalvesaraujo@gmail.com', '58')`);
        await queryRunner.query(`INSERT INTO patients (id, name, document, email, plan_number) VALUES (uuid_generate_v4(), 'Estevan Costa Sousa', '19279995022', 'estevancostasousa@gmail.com', '59')`);
        await queryRunner.query(`INSERT INTO patients (id, name, document, email, plan_number) VALUES (uuid_generate_v4(), 'Julieta Barbosa Rocha', '92575930022', 'julietabarbosarocha@gmail.com', '60')`);
        await queryRunner.query(`INSERT INTO patients (id, name, document, email, plan_number) VALUES (uuid_generate_v4(), 'Isabella Melo Castro', '17486488027', 'isabellamelocastro@gmail.com', '61')`);
        await queryRunner.query(`INSERT INTO patients (id, name, document, email, plan_number) VALUES (uuid_generate_v4(), 'Lucas Azevedo Oliveira', '84959921080', 'lucasazevedooliveira@gmail.com', '62')`);
        await queryRunner.query(`INSERT INTO patients (id, name, document, email, plan_number) VALUES (uuid_generate_v4(), 'Vitória Almeida Silva', '00841057044', 'vitoriaalmeidasilva@gmail.com', '63')`);
        await queryRunner.query(`INSERT INTO patients (id, name, document, email, plan_number) VALUES (uuid_generate_v4(), 'Murilo Azevedo Castro', '97994583075', 'muriloazevedocastro@gmail.com', '64')`);
        await queryRunner.query(`INSERT INTO patients (id, name, document, email, plan_number) VALUES (uuid_generate_v4(), 'Fernanda Silva Martins', '76196551078', 'fernandasilvamartins@gmail.com', '65')`);
        await queryRunner.query(`INSERT INTO patients (id, name, document, email, plan_number) VALUES (uuid_generate_v4(), 'Melissa Rocha Barbosa', '10266935001', 'melissarochabarbosa@gmail.com', '66')`);
        await queryRunner.query(`INSERT INTO patients (id, name, document, email, plan_number) VALUES (uuid_generate_v4(), 'Giovana Cardoso Castro', '36576672020', 'giovanacardosocastro@gmail.com', '67')`);
        await queryRunner.query(`INSERT INTO patients (id, name, document, email, plan_number) VALUES (uuid_generate_v4(), 'Emilly Fernandes Lima', '82121909001', 'emilyfernandeslima@gmail.com', '68')`);
        await queryRunner.query(`INSERT INTO patients (id, name, document, email, plan_number) VALUES (uuid_generate_v4(), 'Kauã Carvalho Souza', '82781558010', 'kauacarvalhosouza@gmail.com', '69')`);
        await queryRunner.query(`INSERT INTO patients (id, name, document, email, plan_number) VALUES (uuid_generate_v4(), 'Martim Oliveira Goncalves', '16933536017', 'martimoliveiragoncalves@gmail.com', '70')`);
        await queryRunner.query(`INSERT INTO patients (id, name, document, email, plan_number) VALUES (uuid_generate_v4(), 'Gabriela Fernandes Correia', '18539843021', 'gabrielafernandescorreia@gmail.com', '71')`);
        await queryRunner.query(`INSERT INTO patients (id, name, document, email, plan_number) VALUES (uuid_generate_v4(), 'André Cardoso Sousa', '11697205011', 'andrecardososousa@gmail.com', '72')`);
        await queryRunner.query(`INSERT INTO patients (id, name, document, email, plan_number) VALUES (uuid_generate_v4(), 'Joao Dias Cardoso', '28089650015', 'joaodiascardoso@gmail.com', '73')`);
        await queryRunner.query(`INSERT INTO patients (id, name, document, email, plan_number) VALUES (uuid_generate_v4(), 'Ana Rodrigues Cavalcanti', '45679058065', 'anarodriguescavalcanti@gmail.com', '74')`);
        await queryRunner.query(`INSERT INTO patients (id, name, document, email, plan_number) VALUES (uuid_generate_v4(), 'Cauã Barbosa Lima', '97988704095', 'cauabarbosalima@gmail.com', '75')`);
        await queryRunner.query(`INSERT INTO patients (id, name, document, email, plan_number) VALUES (uuid_generate_v4(), 'Lavinia Fernandes Dias', '55560531030', 'laviniafernandesdias@gmail.com', '76')`);
        await queryRunner.query(`INSERT INTO patients (id, name, document, email, plan_number) VALUES (uuid_generate_v4(), 'Renan Gomes Cavalcanti', '15540064062', 'renangomescavalcanti@gmail.com', '77')`);
        await queryRunner.query(`INSERT INTO patients (id, name, document, email, plan_number) VALUES (uuid_generate_v4(), 'Letícia Martins Alves', '80867553049', 'leticiamartinsalves@gmail.com', '78')`);
        await queryRunner.query(`INSERT INTO patients (id, name, document, email, plan_number) VALUES (uuid_generate_v4(), 'Tânia Cardoso Gomes', '30750041030', 'taniacardosogomes@gmail.com', '79')`);
        await queryRunner.query(`INSERT INTO patients (id, name, document, email, plan_number) VALUES (uuid_generate_v4(), 'Letícia Gomes Silva', '90264930029', 'leticiagomessilva@gmail.com', '80')`);
        await queryRunner.query(`INSERT INTO patients (id, name, document, email, plan_number) VALUES (uuid_generate_v4(), 'Amanda Gomes Rocha', '62104838010', 'amandagomesrocha@gmail.com', '81')`);
        await queryRunner.query(`INSERT INTO patients (id, name, document, email, plan_number) VALUES (uuid_generate_v4(), 'Matheus Cavalcanti Cardoso', '41766929010', 'matheuscavalcanticardoso@gmail.com', '82')`);
        await queryRunner.query(`INSERT INTO patients (id, name, document, email, plan_number) VALUES (uuid_generate_v4(), 'Carla Azevedo Santos', '07113569048', 'carlaazevedosantos@gmail.com', '83')`);
        await queryRunner.query(`INSERT INTO patients (id, name, document, email, plan_number) VALUES (uuid_generate_v4(), 'Clara Dias Martins', '36959901049', 'claradiasmartins@gmail.com', '84')`);
        await queryRunner.query(`INSERT INTO patients (id, name, document, email, plan_number) VALUES (uuid_generate_v4(), 'Leila Lima Carvalho', '94699629075', 'leilalimacarvalho@gmail.com', '85')`);
        await queryRunner.query(`INSERT INTO patients (id, name, document, email, plan_number) VALUES (uuid_generate_v4(), 'Marisa Silva Cavalcanti', '77378285080', 'marisasilvacavalcanti@gmail.com', '86')`);
        await queryRunner.query(`INSERT INTO patients (id, name, document, email, plan_number) VALUES (uuid_generate_v4(), 'Vitória Araujo Pereira', '99839502000', 'vitoriaaraujopereira@gmail.com', '87')`);
        await queryRunner.query(`INSERT INTO patients (id, name, document, email, plan_number) VALUES (uuid_generate_v4(), 'Tomás Pinto Castro', '06434508077', 'tomaspintocastro@gmail.com', '88')`);
        await queryRunner.query(`INSERT INTO patients (id, name, document, email, plan_number) VALUES (uuid_generate_v4(), 'Ryan Oliveira Rocha', '37755008045', 'ryanoliveirarocha@gmail.com', '89')`);
        await queryRunner.query(`INSERT INTO patients (id, name, document, email, plan_number) VALUES (uuid_generate_v4(), 'Arthur Oliveira Cardoso', '55226109059', 'arthuroliveiracardoso@gmail.com', '90')`);
        await queryRunner.query(`INSERT INTO patients (id, name, document, email, plan_number) VALUES (uuid_generate_v4(), 'Arthur Correia Silva', '80967381002', 'arthurcorreiasilva@gmail.com', '91')`);
        await queryRunner.query(`INSERT INTO patients (id, name, document, email, plan_number) VALUES (uuid_generate_v4(), 'Otávio Pereira Barros', '07047499040', 'otaviopereirabarros@gmail.com', '92')`);
        await queryRunner.query(`INSERT INTO patients (id, name, document, email, plan_number) VALUES (uuid_generate_v4(), 'Bruno Alves Pereira', '01594560021', 'brunoalvespereira@gmail.com', '93')`);
        await queryRunner.query(`INSERT INTO patients (id, name, document, email, plan_number) VALUES (uuid_generate_v4(), 'André Martins Silva', '58674823084', 'andremartinssilva@gmail.com', '94')`);
        await queryRunner.query(`INSERT INTO patients (id, name, document, email, plan_number) VALUES (uuid_generate_v4(), 'João Rocha Azevedo', '36052997095', 'joaorochaazevedo@gmail.com', '95')`);
        await queryRunner.query(`INSERT INTO patients (id, name, document, email, plan_number) VALUES (uuid_generate_v4(), 'Carolina Pereira Silva', '65308201080', 'carolinapereirasilva@gmail.com', '96')`);
        await queryRunner.query(`INSERT INTO patients (id, name, document, email, plan_number) VALUES (uuid_generate_v4(), 'Livia Castro Barros', '07537607036', 'liviacastrobarros@gmail.com', '97')`);
        await queryRunner.query(`INSERT INTO patients (id, name, document, email, plan_number) VALUES (uuid_generate_v4(), 'Vinícius Martins Barros', '07446811030', 'viniciusmartinsbarros@gmail.com', '98')`);
        await queryRunner.query(`INSERT INTO patients (id, name, document, email, plan_number) VALUES (uuid_generate_v4(), 'Breno Santos Pereira', '40752856006', 'brenosantospereira@gmail.com', '99')`);
        await queryRunner.query(`INSERT INTO patients (id, name, document, email, plan_number) VALUES (uuid_generate_v4(), 'Tiago Barros Castro', '36532343013', 'tiagobarroscastro@gmail.com', '100')`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`DELETE FROM patients`);
    }

}
